config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  resources :urls

  put  "/access_tokens/refresh", to: "access_tokens#update", as: :refresh_access_token
  get  "/access_tokens", to: "access_tokens#show", as: :access_token
  get  "/:token", to: "redirections#show", as: :redirect

  namespace :api do
    resources :urls, only: [:index, :create]
  end

  # Defines the root path route ("/")
  root "page#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/url.rb
require 'uri'

class Url < ApplicationRecord
  belongs_to :user

  before_create :set_token

  validates :original_url, presence: true
  validates :original_url, format: { with: URI.regexp }, if: :original_url

  def open_url
    self.increment(:click_analytics, 1)
    self.save
  end

  def shorten_url(url)
    "#{url}#{self.token}"
  end

  private

  def set_token
    begin
      self.token = SecureRandom.hex[0,5].downcase
    end while self.class.exists?(token: token) 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :urls

  before_create :generate_token

  validates :email, presence: true,
                    uniqueness: { case_sensitive: true },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :token, uniqueness: true, allow_blank: true

  def refresh_token
    self.generate_token
    self.save
  end

  protected

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64
      break random_token unless User.exists?(token: random_token)
    end
  end
end

app/controllers/access_tokens_controller.rb
class AccessTokensController < ApplicationController

  def show
    @access_token = current_user.token
  end

  def update
    if current_user.refresh_token
      redirect_to access_token_path, notice: "New token is created."
    else
      redirect_to access_token_path, alert: "Something went wrong when refresh new token."
    end
  end
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController
    protect_from_forgery with: :null_session

    skip_before_action :authenticate_user!
    before_action :authenticate_api!

    def meta_attributes(collection, extra_meta = {})
      {
        current_page: collection.try(:current_page),
        next_page: collection.try(:next_page),
        prev_page: collection.try(:prev_page),
        total_pages: collection.try(:total_pages)
      }.merge(extra_meta)
    end

    protected

    def authenticate_api!
      authenticate_or_request_with_http_token do |token, _|
        User.find_by(token: token)
      end
    end

    def current_user
      @current_user ||= authenticate_api!
    end
  end
end

app/controllers/api/urls_controller.rb
module Api
  class UrlsController < BaseController

    def index
      urls = current_user.urls.page(params[:page] || 1).per(params[:per] || 10)

      render json: {
        urls: urls,
        meta_attributes: meta_attributes(urls)
      }, status: 200
    end

    def create
      url = current_user.urls.new(url_params)

      if url.save
        render json: url, status: 201
      else
        render json: { message: uls.errors.full_messages.to_sentence }, status: 400
      end
    end

    private

    def url_params
      params.permit(:original_url)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    @url = Url.new
  end
end

app/controllers/redirections_controller.rb
class RedirectionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_url, only: [:show]

  def show
    if @url && @url.open_url
      redirect_to @url.original_url, allow_other_host: true
    else
      redirect_to root_url
    end
  end

  private

  def set_url
    @url = Url.find_by(token: params[:token])
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  def index
    @urls = current_user.urls.order(created_at: :desc)
  end

  def create
    @url = current_user.urls.new(url_params)

    if @url.save
      redirect_to url_path @url
    else
      redirect_to root_url, alert: @url.errors.full_messages.to_sentence
    end
  end

  def show; end

  def edit; end
  
  def update
    if @url.update(url_params)
      redirect_to url_path
    else
      render :edit
    end
  end

  def destroy
    if @url.destroy
      redirect_to urls_path
    else
      redirect_to root_url
    end
  end

  private

  def url_params
    params.require(:url).permit(:original_url)
  end

  def set_url
    @url = Url.find_by(id: params[:id])
  end
end

app/helpers/access_tokens_helper.rb
module AccessTokensHelper
end

app/helpers/api/v1/private_api_keys_helper.rb
module Api::V1::PrivateApiKeysHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/redirections_helper.rb
module RedirectionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/access_tokens/show.html.erb
<div
  class="container"
  style="width: 50%; margin-top: 10vh;"
>
  <p><i>Your Access Token</i></p>
  <h4>
    <%= @access_token %>
  </h4>
  <hr />
  <ul class="menu">
    <li><%= link_to "New Shorten", root_url %></li>
    <li><%= link_to "URL List", urls_path %></li>
    <li><%= button_to "Refresh Access Token", refresh_access_token_path, method: :put %></li>
  </ul>
</div>

<style type="text/css">
  p, h2, h3, h4 {
    text-align: center;
  }

  ul.menu {
    text-align: center;
  }

  ul.menu > li {
    border-right: solid 1px;
    text-transform: uppercase;
    text-decoration: none;
    display: inline-block;
    padding-left: 7.5px;
    padding-right: 7.5px;
  }

  ul.menu > li:last-child {
    border-right: unset;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<div
  class="container"
  style="width: 50%; margin-top: 25vh;"
>
  <h3>Shorten your URL now</h3>
  <%= form_for(@url, action: :urls_path, class: "form-inline") do |form| %>
    <div class="input-group input-group-lg">
      <%= form.text_field :original_url, class: "form-control input-lg", placeholder: "Your URL here...", style: "border-radius: 5px 0 0 5px;" %>
      <%= form.submit "Shorten", class: "btn btn-lg btn-secondary", style: "border-radius: 0 5px 5px 0;" %>
    </div>
  <% end %>
  <ul class="menu" style="margin-top: 10px;">
    <li style="font-size: 1.5rem;"><%= link_to "URL List", urls_path %></li>
    <li style="font-size: 1.5rem;"><%= link_to "Get API Access Token", access_token_path %></li>
    <li style="font-size: 1.5rem;"><%= button_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  </ul>
</div>

<style type="text/css">
  p, h2, h3, h4 {
    text-align: center;
  }

  ul.menu {
    text-align: center;
  }

  ul.menu > li {
    border-right: solid 1px;
    text-transform: uppercase;
    text-decoration: none;
    display: inline-block;
    padding-left: 7.5px;
    padding-right: 7.5px;
  }

  ul.menu > li:last-child {
    border-right: unset;
  }
</style>

app/views/redirections/new.html.erb
#new.html.erb

app/views/urls/edit.html.erb
<div
  class="container"
  style="width: 50%; margin-top: 25vh;"
>
  <h3>You're currently on the editing page</h3>
  <%= form_for(@url, action: :edit_url_path, class: "form-inline") do |form| %>
    <div class="input-group input-group-lg">
      <%= form.text_field :original_url, class: "form-control input-lg", placeholder: "Your URL here...", style: "border-radius: 5px 0 0 5px;" %>
      <%= form.submit "Update", class: "btn btn-lg btn-secondary", style: "border-radius: 0 5px 5px 0;" %>
    </div>
  <% end %>
  <ul class="menu" style="margin-top: 10px;">
    <li style="font-size: 1.5rem;"><%= link_to "<< Back", url_path %></li>
    <li style="font-size: 1.5rem;"><%= link_to "New Shorten", urls_path %></li>
    <li style="font-size: 1.5rem;"><%= button_to "Destroy", @url, method: :delete %></li>
  </ul>
</div>

<style type="text/css">
  p, h2, h3, h4 {
    text-align: center;
  }

  ul.menu {
    text-align: center;
  }

  ul.menu > li {
    border-right: solid 1px;
    text-transform: uppercase;
    text-decoration: none;
    display: inline-block;
    padding-left: 7.5px;
    padding-right: 7.5px;
  }

  ul.menu > li:last-child {
    border-right: unset;
  }
</style>

app/views/urls/index.html.erb
<div
  class="container"
  style="margin-top: 5vh;"
>
  <h3>Shorten your URL now</h3>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Original URL</th>
        <th scope="col">Shorten URL</th>
        <th scope="col" style="text-align: center;">Total Clicks</th>
        <th scope="col" style="text-align: center;">Created Date</th>
        <th scope="col" style="text-align: center;"></th>
      </tr>
    </thead>
    <tbody>
      <% if @urls.any? %>
        <% @urls.each_with_index do |url, index| %>
          <tr>
            <th scope="row"><%= index + 1 %></th>
            <td><%= link_to url.original_url, url.original_url, target: "_blank" %></td>
            <td><%= link_to url.shorten_url(root_url), redirect_path(url.token), target: "_blank" %></td>
            <td style="text-align: center;"><%= url.click_analytics %></td>
            <td style="text-align: center;"><%= url.created_at.strftime("%d/%m/%Y") %></td>
            <td style="text-align: center;">
              <a href="#">
                <span class="label label-default"><%= link_to "Show", url_path(url) %></span>
              </a>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <th>nothing to show</th>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr />
  <ul class="menu" style="margin-top: 10px;">
    <li style="font-size: 1.5rem;"><%= link_to "New Shorten", root_url %></li>
  </ul>
</div>

<style type="text/css">
  p, h2, h3, h4 {
    text-align: center;
  }

  ul.menu {
    text-align: center;
  }

  ul.menu > li {
    border-right: solid 1px;
    text-transform: uppercase;
    text-decoration: none;
    display: inline-block;
    padding-left: 7.5px;
    padding-right: 7.5px;
  }

  ul.menu > li:last-child {
    border-right: unset;
  }
</style>

app/views/urls/show.html.erb
<div
  class="container"
  style="width: 50%; margin-top: 10vh;"
>
  <h2><i>URL Details</i></h2>
  <h4>
    <%= link_to @url.original_url, @url.original_url, target: "_blank" %>
  </h4>
  <h4><i>Your shorten URL as below:</i></h4>
  <h4>
    <i>
      <%= link_to @url.shorten_url(root_url), redirect_path(@url.token), target: "_blank" %>
    </i>
  </h4>
  <hr />
  <h3>
    <i>Your shorten URL got total <span style="font-size: 2.2rem; font-weight: bold;"><%= @url.click_analytics %></span> click(s)</i>
  </h3>
  <hr />
  <ul class="menu">
    <li><%= link_to "New Shorten", root_url %></li>
    <li><%= link_to "URL List", urls_path %></li>
    <li><%= link_to "Edit", edit_url_path %></li>
    <li><%= button_to "Destroy", @url, method: :delete %></li>
  </ul>
</div>

<style type="text/css">
  p, h2, h3, h4 {
    text-align: center;
  }

  ul.menu {
    text-align: center;
  }

  ul.menu > li {
    border-right: solid 1px;
    text-transform: uppercase;
    text-decoration: none;
    display: inline-block;
    padding-left: 7.5px;
    padding-right: 7.5px;
  }

  ul.menu > li:last-child {
    border-right: unset;
  }
</style>